.TH sound-match 1  "January 9, 2013" "version 0.9" "USER COMMANDS"
.SH NAME
sound-match \- A tool to find occurences of an audio clip in an audio file
.SH SYNOPSIS
.B sound-match <needle.wav> <haystack.wav>

.SH DESCRIPTION

The tools all make use of cross correlation, which can be computed through the fourier transform.

Note that all the tools will need access to write to a file called <tool>.log where various information about a run will be stored.


.SH EXIT STATUS
sound-match returns 0 unless some error occured.
.SH AUTHOR
Jesper Sindahl Nielsen <jsn@statsbiblioteket.dk>
